import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module";
import { PrismaService } from "./infrastructure/database/prisma.service";
import * as fs from "fs";
import * as path from "path";
import { Decimal } from "decimal.js";
import * as crypto from "crypto";

// Types for the JSON structure
interface ProductJson {
  code: string;
  name: string;
  categoryCode: string;
  baseUnit: string;
  basePrice: number | null;
  sheetRow?: number;
  width: number | null;
  length: number | null;
  kgPerUnit: number | null;
}

/**
 * Generates a deterministic price based on the product code hash.
 * This ensures consistency across multiple seed runs.
 */
function generateDeterministicPrice(
  code: string,
  min: number,
  max: number,
): Decimal {
  const hash = crypto.createHash("md5").update(code).digest("hex");
  const hashInt = parseInt(hash.substring(0, 8), 16);
  const price = min + (hashInt % (max - min));
  return new Decimal(price);
}

async function bootstrap() {
  const app = await NestFactory.createApplicationContext(AppModule);
  const prisma = app.get(PrismaService);

  try {
    console.log(`📦 Loaded ${productsJson.length} products from JSON.`);

    // 1. Pre-fetch reference data for performance
    const categories = await prisma.category.findMany();
    const categoryMap = new Map(categories.map((c) => [c.code, c.id]));

    const units = await prisma.unit.findMany();
    const unitCodes = new Set(units.map((u) => u.code));

    let successCount = 0;
    let skipCount = 0;

    for (const item of productsJson) {
      const categoryId = categoryMap.get(item.categoryCode);

      if (!categoryId) {
        console.warn(
          `⚠️ Skipping product [${item.code}]: Category [${item.categoryCode}] not found.`,
        );
        skipCount++;
        continue;
      }

      if (!unitCodes.has(item.baseUnit)) {
        console.warn(
          `⚠️ Skipping product [${item.code}]: Base unit [${item.baseUnit}] not found.`,
        );
        skipCount++;
        continue;
      }

      // Logic for missing fields
      const costPrice = generateDeterministicPrice(item.code, 50000, 150000);
      const basePrice = item.basePrice
        ? new Decimal(item.basePrice)
        : costPrice.mul(1.3);

      // dimensions
      const length = item.length ? new Decimal(item.length) : null;
      const width = item.width ? new Decimal(item.width) : null;

      // 2. Upsert Product
      const product = await prisma.product.upsert({
        where: { code: item.code },
        update: {
          name: item.name,
          categoryId,
          baseUnit: item.baseUnit,
          basePrice,
          costPrice,
          length,
          width,
        },
        create: {
          code: item.code,
          name: item.name,
          categoryId,
          baseUnit: item.baseUnit,
          basePrice,
          costPrice,
          length,
          width,
          reorderThreshold: 10,
        },
      });

      // 3. Initialize Inventory
      await prisma.inventory.upsert({
        where: { productId: product.id },
        update: {}, // Don't reset quantity if already exists
        create: {
          productId: product.id,
          quantity: 0,
          unitCode: item.baseUnit,
        },
      });

      // 4. Create Unit Conversions
      const conversions: {
        productId: number;
        fromUnit: string;
        toUnit: string;
        factor: Decimal;
      }[] = [];

      // Roll to Meter
      if (item.length && item.length > 0 && unitCodes.has("m")) {
        conversions.push({
          productId: product.id,
          fromUnit: item.baseUnit,
          toUnit: "m",
          factor: new Decimal(item.length),
        });
      }

      // Roll to Kilogram
      if (item.kgPerUnit && item.kgPerUnit > 0 && unitCodes.has("kg")) {
        conversions.push({
          productId: product.id,
          fromUnit: item.baseUnit,
          toUnit: "kg",
          factor: new Decimal(item.kgPerUnit),
        });
      }

      // Roll to Square Meter
      if (
        item.length &&
        item.width &&
        item.length > 0 &&
        item.width > 0 &&
        unitCodes.has("m2")
      ) {
        conversions.push({
          productId: product.id,
          fromUnit: item.baseUnit,
          toUnit: "m2",
          factor: new Decimal(item.length).mul(item.width),
        });
      }

      for (const conv of conversions) {
        await prisma.unitConversion
          .upsert({
            where: {
              // Since we don't have a unique constraint on productId/fromUnit/toUnit in schema.prisma,
              // we use findFirst + create/update or just skip for simplicity if we can't upsert by unique key.
              // Wait, looking at the schema, UnitConversion has an auto-increment ID but NO UNIQUE CONSTRAINT on the triple.
              // I should check if there's a unique index in the DB or if I should just find and update.
              id: -1, // Dummy ID to trigger search
            },
            // Fallback: Check if exists first
            update: {},
            create: conv,
          })
          .catch(async () => {
            // Alternative approach for tables without unique keys:
            const existing = await prisma.unitConversion.findFirst({
              where: {
                productId: product.id,
                fromUnit: conv.fromUnit,
                toUnit: conv.toUnit,
              },
            });
            if (!existing) {
              await prisma.unitConversion.create({ data: conv });
            } else {
              await prisma.unitConversion.update({
                where: { id: existing.id },
                data: { factor: conv.factor },
              });
            }
          });
      }

      successCount++;
      if (successCount % 100 === 0) {
        console.log(`✅ Progress: Processed ${successCount} products...`);
      }
    }

    console.log(`\n✨ Seeding Completed!`);
    console.log(`🎉 Successfully seeded: ${successCount} products`);
    console.log(`⚠️ Skipped: ${skipCount} products`);
  } catch (error) {
    console.error("❌ Error seeding products:", error);
    process.exit(1);
  } finally {
    await app.close();
    process.exit(0);
  }
}

bootstrap().catch((err) => {
  console.error(err);
  process.exit(1);
});

const productsJson = [
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_180-0_914_50M-001",
    name: "PP tự dính 180 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 6,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.0,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_180-1_07_50M-002",
    name: "PP tự dính 180 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 7,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 7.2,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_180-1_27_50M-003",
    name: "PP tự dính 180 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 8,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 8.5,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_180-1_52_50M-004",
    name: "PP tự dính 180 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 9,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 10.7,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_160-0_914_50M-005",
    name: "PP tự dính 160 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 10,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 5.6,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_160-1_07_50M-006",
    name: "PP tự dính 160 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 11,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 6.6,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_160-1_27_50M-007",
    name: "PP tự dính 160 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 12,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 7.6,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_160-1_52_50M-008",
    name: "PP tự dính 160 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 13,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 9.2,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_BS180-0_914_50M-009",
    name: "PP mã BS180 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 14,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 4.8,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_BS180-1_07_50M-010",
    name: "PP mã BS180 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 15,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 5.5,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_BS180-1_27_50M-011",
    name: "PP mã BS180 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 16,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 6.6,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_WP180-0_61_50M-012",
    name: "PP mã WP180 0.61*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 17,
    width: 0.61,
    length: 50.0,
    kgPerUnit: 4.5,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_WP180-0_76_50M-013",
    name: "PP mã WP180 0.76*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 18,
    width: 0.76,
    length: 50.0,
    kgPerUnit: 5.6,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_WP180-0_914_50M-014",
    name: "PP mã WP180 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 19,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.6,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_MA_IEU-1_27_50M-015",
    name: "PP tự dính mã điều 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 20,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 8.4,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_DAY-0_61_50M-016",
    name: "PP tự dính dày 0.61*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 21,
    width: 0.61,
    length: 50.0,
    kgPerUnit: 4.3,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_HANG_AT-0_61_50M-017",
    name: "PP tự dính - hàng đặt 0.61*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 22,
    width: 0.61,
    length: 50.0,
    kgPerUnit: 6.0,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_HANG_AT-0_76_50M-018",
    name: "PP tự dính - hàng đặt 0.76*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 23,
    width: 0.76,
    length: 50.0,
    kgPerUnit: 8.0,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_HANG_AT-0_914_50M-019",
    name: "PP tự dính - hàng đặt 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 24,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 8.5,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_HANG_AT-1_12_50M-020",
    name: "PP tự dính - hàng đặt 1.12*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 25,
    width: 1.12,
    length: 50.0,
    kgPerUnit: 10.8,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_WP190-0_914_30M-021",
    name: "PP mã WP190 0.914*30m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 26,
    width: 0.914,
    length: 30.0,
    kgPerUnit: 4.7,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_WP190-1_27_50M-022",
    name: "PP mã WP190 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 27,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 7.7,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO160-0_914_50M-023",
    name: "PP tự dính ECO160 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 28,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 5.9,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO160-1_07_50M-024",
    name: "PP tự dính ECO160 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 29,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 6.8,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO160-1_27_50M-025",
    name: "PP tự dính ECO160 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 30,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 8.2,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO160-1_52_50M-026",
    name: "PP tự dính ECO160 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 31,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 9.4,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO190-0_914_50M-027",
    name: "PP tự dính ECO190 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 32,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.3,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO190-1_07_50M-028",
    name: "PP tự dính ECO190 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 33,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 6.8,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO190-1_27_50M-029",
    name: "PP tự dính ECO190 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 34,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 8.3,
  },
  {
    code: "PP_MANG_DECAL-PP_TU_DINH_ECO190-1_52_50M-030",
    name: "PP tự dính ECO190 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 35,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 10.2,
  },
  {
    code: "PP_MANG_DECAL-PP_ECO200-0_914_50M-031",
    name: "PP ECO200 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 36,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.2,
  },
  {
    code: "PP_MANG_DECAL-PP_ECO200-1_07_50M-032",
    name: "PP ECO200 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 37,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 7.0,
  },
  {
    code: "PP_MANG_DECAL-PP_ECO200-1_27_50M-033",
    name: "PP ECO200 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 38,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 8.4,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_BACKLIT-0_914_50M-034",
    name: "PP mã backlit 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 39,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 7.6,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_BACKLIT-1_07_50M-035",
    name: "PP mã backlit 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 40,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 8.9,
  },
  {
    code: "PP_MANG_DECAL-PP_MA_BACKLIT-1_27_50M-036",
    name: "PP mã backlit 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 41,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 10.9,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_VANG-0_914_50M-037",
    name: "PVC mặt bóng - đế vàng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 42,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 7.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_VANG-1_07_50M-038",
    name: "PVC mặt bóng - đế vàng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 43,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 9.0,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_VANG-1_27_50M-039",
    name: "PVC mặt bóng - đế vàng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 44,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 10.6,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_VANG-1_52_50M-040",
    name: "PVC mặt bóng - đế vàng 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 45,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 13.6,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_TRANG-0_635_50M-041",
    name: "PVC mặt bóng - đế trắng 0.635*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 46,
    width: 0.635,
    length: 50.0,
    kgPerUnit: 5.6,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_TRANG-0_914_50M-042",
    name: "PVC mặt bóng - đế trắng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 47,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 7.6,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_TRANG-1_07_50M-043",
    name: "PVC mặt bóng - đế trắng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 48,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 9.2,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_TRANG-1_27_50M-044",
    name: "PVC mặt bóng - đế trắng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 49,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 11.0,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_TRANG-1_52_50M-045",
    name: "PVC mặt bóng - đế trắng 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 50,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 12.6,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_E_TRANG-1_52_20M-046",
    name: "PVC mặt bóng - đế trắng 1.52*20m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 51,
    width: 1.52,
    length: 20.0,
    kgPerUnit: 8.7,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_MONG-0_914_50M-047",
    name: "PVC mặt bóng - mỏng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 52,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_MONG-0_914_50M-048",
    name: "PVC mặt bóng - mỏng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 53,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_MONG-1_07_50M-049",
    name: "PVC mặt bóng - mỏng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 54,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 8.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_MONG-1_07_50M-050",
    name: "PVC mặt bóng - mỏng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 55,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 8.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_MONG-1_07_45M-051",
    name: "PVC mặt bóng - mỏng 1.07*45m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 56,
    width: 1.07,
    length: 45.0,
    kgPerUnit: 8.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_MONG-1_27_50M-052",
    name: "PVC mặt bóng - mỏng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 57,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 9.4,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_BONG_MONG-1_27_50M-053",
    name: "PVC mặt bóng - mỏng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 58,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 9.4,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_TRANG-0_635_50M-054",
    name: "PVC mặt mờ - đế trắng 0.635*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 59,
    width: 0.635,
    length: 50.0,
    kgPerUnit: 5.7,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_TRANG-0_635_50M-055",
    name: "PVC mặt mờ - đế trắng 0.635*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 60,
    width: 0.635,
    length: 50.0,
    kgPerUnit: 5.6,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_TRANG-0_914_50M-056",
    name: "PVC mặt mờ - đế trắng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 61,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 8.3,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_TRANG-1_07_50M-057",
    name: "PVC mặt mờ - đế trắng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 62,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 9.3,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_TRANG-1_27_50M-058",
    name: "PVC mặt mờ - đế trắng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 63,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 11.1,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_TRANG-1_52_50M-059",
    name: "PVC mặt mờ - đế trắng 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 64,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 13.2,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_MONG-0_635_50M-060",
    name: "PVC mặt mờ - mỏng 0.635*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 65,
    width: 0.635,
    length: 50.0,
    kgPerUnit: 4.7,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_MONG-0_914_50M-061",
    name: "PVC mặt mờ - mỏng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 66,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.9,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_MONG-0_914_50M-062",
    name: "PVC mặt mờ - mỏng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 67,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 6.9,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_MONG-1_07_50M-063",
    name: "PVC mặt mờ - mỏng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 68,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 7.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_MONG-1_07_50M-064",
    name: "PVC mặt mờ - mỏng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 69,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 7.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_MONG-1_27_50M-065",
    name: "PVC mặt mờ - mỏng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 70,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 9.4,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_MONG-1_27_50M-066",
    name: "PVC mặt mờ - mỏng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 71,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 9.4,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_VANG-0_914_50M-067",
    name: "PVC mặt mờ - đế vàng 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 72,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 7.7,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_VANG-1_07_50M-068",
    name: "PVC mặt mờ - đế vàng 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 73,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 9.1,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_VANG-1_27_50M-069",
    name: "PVC mặt mờ - đế vàng 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 74,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 10.6,
  },
  {
    code: "PP_MANG_DECAL-PVC_MAT_MO_E_VANG-1_52_50M-070",
    name: "PVC mặt mờ - đế vàng 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 75,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 13.0,
  },
  {
    code: "PP_MANG_DECAL-PVC_NHAM-1_27_50M-071",
    name: "PVC nhám 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 76,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 17.8,
  },
  {
    code: "PP_MANG_DECAL-PVC_KIM_TUYEN-0_635_50M-072",
    name: "PVC kim tuyến 0.635*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 77,
    width: 0.635,
    length: 50.0,
    kgPerUnit: 9.5,
  },
  {
    code: "PP_MANG_DECAL-PVC_KIM_TUYEN-1_27_50M-073",
    name: "PVC kim tuyến 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 78,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 13.6,
  },
  {
    code: "PP_MANG_DECAL-MANG_PET-0_914_50M-074",
    name: "Màng PET 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 79,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 14.1,
  },
  {
    code: "PP_MANG_DECAL-MANG_PET-1_07_50M-075",
    name: "Màng PET 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 80,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 16.4,
  },
  {
    code: "PP_MANG_DECAL-MANG_PET-1_27_50M-076",
    name: "Màng PET 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 81,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 19.5,
  },
  {
    code: "PP_MANG_DECAL-MANG_PET-1_52_50M-077",
    name: "Màng PET 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 82,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 23.2,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_HANG_EU-0_914_50M-078",
    name: "Màng PVC decal - hàng đều 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 83,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 12.6,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_HANG_EU-1_07_50M-079",
    name: "Màng PVC decal - hàng đều 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 84,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 14.1,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_HANG_EU-1_27_50M-080",
    name: "Màng PVC decal - hàng đều 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 85,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 16.7,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_HANG_EU-1_52_50M-081",
    name: "Màng PVC decal - hàng đều 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 86,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 20.8,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_PVC120-0_914_50M-082",
    name: "Màng PVC decal PVC120 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 87,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 12.4,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_PVC120-1_52_50M-083",
    name: "Màng PVC decal PVC120 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 88,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 20.0,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_PVC140-0_914_50M-084",
    name: "Màng PVC decal PVC140 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 89,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 15.5,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_PVC140-1_07_50M-085",
    name: "Màng PVC decal PVC140 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 90,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 17.0,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_PVC140-1_27_50M-086",
    name: "Màng PVC decal PVC140 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 91,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 20.7,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_PVC140-1_52_50M-087",
    name: "Màng PVC decal PVC140 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 92,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 24.6,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHONG_LOGO-0_914_50M-088",
    name: "Màng PVC decal - không logo 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 93,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 12.2,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHONG_LOGO-1_07_50M-089",
    name: "Màng PVC decal - không logo 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 94,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 13.6,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHONG_LOGO-1_27_50M-090",
    name: "Màng PVC decal - không logo 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 95,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 16.0,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHONG_LOGO-1_52_50M-091",
    name: "Màng PVC decal - không logo 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 96,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 19.8,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH120-0_914_50M-092",
    name: "Màng PVC decal - KHH120 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 97,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 12.5,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH120-1_07_50M-093",
    name: "Màng PVC decal - KHH120 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 98,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 14.4,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH120-1_27_50M-094",
    name: "Màng PVC decal - KHH120 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 99,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 17.3,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH120-1_52_50M-095",
    name: "Màng PVC decal - KHH120 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 100,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 21.6,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH150-0_914_50M-096",
    name: "Màng PVC decal - KHH150 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 101,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 15.4,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH150-1_07_50M-097",
    name: "Màng PVC decal - KHH150 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 102,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 18.0,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH150-1_27_50M-098",
    name: "Màng PVC decal - KHH150 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 103,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 20.9,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH150-1_52_50M-099",
    name: "Màng PVC decal - KHH150 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 104,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 25.8,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH_P150-0_914_50M-100",
    name: "Màng PVC decal - KHH-P150 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 105,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 15.1,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH_P150-1_07_50M-101",
    name: "Màng PVC decal - KHH-P150 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 106,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 17.4,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH_P150-1_27_50M-102",
    name: "Màng PVC decal - KHH-P150 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 107,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 20.3,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_DECAL_KHH_P150-1_52_50M-103",
    name: "Màng PVC decal - KHH-P150 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 108,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 24.6,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_TRONG-0_914_50M-104",
    name: "Màng PVC trong 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 109,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 12.1,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_TRONG-1_07_50M-105",
    name: "Màng PVC trong 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 110,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 13.8,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_TRONG-1_27_50M-106",
    name: "Màng PVC trong 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 111,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 16.1,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_TRONG-1_52_50M-107",
    name: "Màng PVC trong 1.52*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 112,
    width: 1.52,
    length: 50.0,
    kgPerUnit: 20.2,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_TRONG-0_914_50M-108",
    name: "Màng PVC trong 0.914*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 113,
    width: 0.914,
    length: 50.0,
    kgPerUnit: 11.7,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_TRONG-1_07_50M-109",
    name: "Màng PVC trong 1.07*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 114,
    width: 1.07,
    length: 50.0,
    kgPerUnit: 13.7,
  },
  {
    code: "PP_MANG_DECAL-MANG_PVC_TRONG-1_27_50M-110",
    name: "Màng PVC trong 1.27*50m",
    categoryCode: "PP_MANG_DECAL",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 115,
    width: 1.27,
    length: 50.0,
    kgPerUnit: 16.8,
  },
  {
    code: "LY-LY_SU_TRANG-CHU_EN-001",
    name: "LY SỨ TRẮNG Chữ Đen （普通白杯）",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 6,
  },
  {
    code: "LY-LY_SU_TRANG-LY_DAY-002",
    name: "LY SỨ TRẮNG Ly Dày",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 7,
  },
  {
    code: "LY-LY_LONG_MAU_SOC_QUAI-O-003",
    name: "LY LỒNG MÀU SỌC QUAI ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 8,
  },
  {
    code: "LY-LY_LONG_MAU_SOC_QUAI-EN-004",
    name: "LY LỒNG MÀU SỌC QUAI ĐEN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 9,
  },
  {
    code: "LY-LY_LONG_MAU_SOC_QUAI-CAM-005",
    name: "LY LỒNG MÀU SỌC QUAI CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 10,
  },
  {
    code: "LY-LY_LONG_MAU_SOC_QUAI-VANG-006",
    name: "LY LỒNG MÀU SỌC QUAI VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 11,
  },
  {
    code: "LY-LY_LONG_MAU_SOC_QUAI-XANH_COM-007",
    name: "LY LỒNG MÀU SỌC QUAI XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 12,
  },
  {
    code: "LY-LY_LONG_MAU_SOC_QUAI-XANH_BIEN-008",
    name: "LY LỒNG MÀU SỌC QUAI XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 13,
  },
  {
    code: "LY-LY_LONG_MAU_SOC_QUAI-HONG-009",
    name: "LY LỒNG MÀU SỌC QUAI HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 14,
  },
  {
    code: "LY-LY_MUONG_MAU_12OZ_BAU-O-010",
    name: "LY MUỖNG MÀU 12oz - BẦU ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 15,
  },
  {
    code: "LY-LY_MUONG_MAU_12OZ_BAU-EN-011",
    name: "LY MUỖNG MÀU 12oz - BẦU ĐEN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 16,
  },
  {
    code: "LY-LY_MUONG_MAU_12OZ_BAU-CAM-012",
    name: "LY MUỖNG MÀU 12oz - BẦU CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 17,
  },
  {
    code: "LY-LY_MUONG_MAU_12OZ_BAU-VANG-013",
    name: "LY MUỖNG MÀU 12oz - BẦU VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 18,
  },
  {
    code: "LY-LY_MUONG_MAU_12OZ_BAU-XANH_COM-014",
    name: "LY MUỖNG MÀU 12oz - BẦU XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 19,
  },
  {
    code: "LY-LY_MUONG_MAU_12OZ_BAU-XANH_BIEN-015",
    name: "LY MUỖNG MÀU 12oz - BẦU XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 20,
  },
  {
    code: "LY-LY_MUONG_MAU_12OZ_BAU-HONG-016",
    name: "LY MUỖNG MÀU 12oz - BẦU HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 21,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_TRANG-O-017",
    name: "LY LỒNG MÀU - QUAI TRẮNG ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 22,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_TRANG-EN-018",
    name: "LY LỒNG MÀU - QUAI TRẮNG ĐEN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 23,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_TRANG-CAM-019",
    name: "LY LỒNG MÀU - QUAI TRẮNG CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 24,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_TRANG-VANG-020",
    name: "LY LỒNG MÀU - QUAI TRẮNG VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 25,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_TRANG-XANH_COM-021",
    name: "LY LỒNG MÀU - QUAI TRẮNG XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 26,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_TRANG-XANH_BIEN-022",
    name: "LY LỒNG MÀU - QUAI TRẮNG XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 27,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_TRANG-HONG-023",
    name: "LY LỒNG MÀU - QUAI TRẮNG HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 28,
  },
  {
    code: "LY-LY_OI_MAU_MO_LONG_MAU_2_CHAM-O-024",
    name: "LY ĐỔI MÀU MỜ - LỒNG MÀU (2 CHẤM) ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 29,
  },
  {
    code: "LY-LY_OI_MAU_MO_LONG_MAU_2_CHAM-CAM-025",
    name: "LY ĐỔI MÀU MỜ - LỒNG MÀU (2 CHẤM) CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 30,
  },
  {
    code: "LY-LY_OI_MAU_MO_LONG_MAU_2_CHAM-VANG-026",
    name: "LY ĐỔI MÀU MỜ - LỒNG MÀU (2 CHẤM) VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 31,
  },
  {
    code: "LY-LY_OI_MAU_MO_LONG_MAU_2_CHAM-XANH_COM-027",
    name: "LY ĐỔI MÀU MỜ - LỒNG MÀU (2 CHẤM) XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 32,
  },
  {
    code: "LY-LY_OI_MAU_MO_LONG_MAU_2_CHAM-XANH_BIEN-028",
    name: "LY ĐỔI MÀU MỜ - LỒNG MÀU (2 CHẤM) XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 33,
  },
  {
    code: "LY-LY_OI_MAU_MO_LONG_MAU_2_CHAM-HONG-029",
    name: "LY ĐỔI MÀU MỜ - LỒNG MÀU (2 CHẤM) HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 34,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_MAU-CAM-030",
    name: "LY VIỀN MÀU - QUAI MÀU CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 35,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_MAU-XANH_COM-031",
    name: "LY VIỀN MÀU - QUAI MÀU XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 36,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_MAU-VANG-032",
    name: "LY VIỀN MÀU - QUAI MÀU VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 37,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_MAU-O-033",
    name: "LY VIỀN MÀU - QUAI MÀU ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 38,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_MAU-XANH_BIEN-034",
    name: "LY VIỀN MÀU - QUAI MÀU XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 39,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_MAU-HONG-035",
    name: "LY VIỀN MÀU - QUAI MÀU HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 40,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_MAU-O-036",
    name: "LY LỒNG MÀU - QUAI MÀU ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 41,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_MAU-XANH_COM-037",
    name: "LY LỒNG MÀU - QUAI MÀU XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 42,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_MAU-VANG-038",
    name: "LY LỒNG MÀU - QUAI MÀU VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 43,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_MAU-XANH_BIEN-039",
    name: "LY LỒNG MÀU - QUAI MÀU XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 44,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_MAU-XANH_TIM-040",
    name: "LY LỒNG MÀU - QUAI MÀU XANH TÍM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 45,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_MAU-HONG-041",
    name: "LY LỒNG MÀU - QUAI MÀU HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 46,
  },
  {
    code: "LY-LY_LONG_MAU_QUAI_MAU-CAM-042",
    name: "LY LỒNG MÀU - QUAI MÀU CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 47,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_TIM-O-043",
    name: "LY VIỀN MÀU - QUAI TIM ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 48,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_TIM-CAM-044",
    name: "LY VIỀN MÀU - QUAI TIM CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 49,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_TIM-XANH_COM-045",
    name: "LY VIỀN MÀU - QUAI TIM XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 50,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_TIM-VANG-046",
    name: "LY VIỀN MÀU - QUAI TIM VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 51,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_TIM-XANH_BIEN-047",
    name: "LY VIỀN MÀU - QUAI TIM XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 52,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_TIM-HONG-048",
    name: "LY VIỀN MÀU - QUAI TIM HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 53,
  },
  {
    code: "LY-LY_VIEN_MAU_QUAI_TIM-O-049",
    name: "LY VIỀN MÀU - QUAI TIM ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 54,
  },
  {
    code: "LY-LY_LONG_MAU_MUONG-CAM-050",
    name: "LY LỒNG MÀU - MUỖNG CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 55,
  },
  {
    code: "LY-LY_LONG_MAU_MUONG-XANH_TIM-051",
    name: "LY LỒNG MÀU - MUỖNG XANH TÍM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 56,
  },
  {
    code: "LY-LY_LONG_MAU_MUONG-XANH_BIEN-052",
    name: "LY LỒNG MÀU - MUỖNG XANH BIỂN",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 57,
  },
  {
    code: "LY-LY_LONG_MAU_MUONG-VANG-053",
    name: "LY LỒNG MÀU - MUỖNG VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 58,
  },
  {
    code: "LY-LY_LONG_MAU_MUONG-HONG-054",
    name: "LY LỒNG MÀU - MUỖNG HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 59,
  },
  {
    code: "LY-MUONG-CAM-055",
    name: "MUỖNG CAM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 60,
  },
  {
    code: "LY-MUONG-O-056",
    name: "MUỖNG ĐỎ",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 61,
  },
  {
    code: "LY-MUONG-VANG-057",
    name: "MUỖNG VÀNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 62,
  },
  {
    code: "LY-MUONG-HONG-058",
    name: "MUỖNG HỒNG",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 63,
  },
  {
    code: "LY-MUONG-XANH_COM-059",
    name: "MUỖNG XANH CỐM",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 64,
  },
  {
    code: "LY-MUONG-NAU-060",
    name: "MUỖNG NÂU",
    categoryCode: "LY",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 65,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_KODAK_MAT_BONG-0_61_30M-001",
    name: "Giấy in ảnh kodak mặt bóng 0.61*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 6,
    width: 0.61,
    length: 30.0,
    kgPerUnit: 5.4,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_KODAK_MAT_BONG-0_762_30M-002",
    name: "Giấy in ảnh kodak mặt bóng 0.762*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 7,
    width: 0.762,
    length: 30.0,
    kgPerUnit: 6.7,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_KODAK_MAT_BONG-0_914_30M-003",
    name: "Giấy in ảnh kodak mặt bóng 0.914*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 8,
    width: 0.914,
    length: 30.0,
    kgPerUnit: 8.0,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_KODAK_MAT_MO-0_61_30M-004",
    name: "Giấy in ảnh Kodak mặt mờ 0.61*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 9,
    width: 0.61,
    length: 30.0,
    kgPerUnit: 5.5,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_KODAK_MAT_MO-0_762_30M-005",
    name: "Giấy in ảnh Kodak mặt mờ 0.762*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 10,
    width: 0.762,
    length: 30.0,
    kgPerUnit: 6.8,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_MAT_BONG_260G_KHONG_LOGO-0_762_30M-006",
    name: "Giáy in ảnh mặt bóng 260g không logo 0.762*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 11,
    width: 0.762,
    length: 30.0,
    kgPerUnit: 6.6,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_MAT_BONG_260G_KHONG_LOGO-0_914_30M-007",
    name: "Giáy in ảnh mặt bóng 260g không logo 0.914*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 12,
    width: 0.914,
    length: 30.0,
    kgPerUnit: 8.7,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_MAT_BONG_240G_KHONG_LOGO-0_762_30M-008",
    name: "Giấy in ảnh mặt bóng 240g không logo 0.762*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 13,
    width: 0.762,
    length: 30.0,
    kgPerUnit: 6.5,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_MAT_BONG_240G_KHONG_LOGO-0_914_30M-009",
    name: "Giấy in ảnh mặt bóng 240g không logo 0.914*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 14,
    width: 0.914,
    length: 30.0,
    kgPerUnit: 7.9,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_MAT_MO_240G_KHONG_LOGO-0_61_30M-010",
    name: "Giấy in ảnh mặt mờ 240g không logo 0.61*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 15,
    width: 0.61,
    length: 30.0,
    kgPerUnit: 5.0,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_MO-0_508_30M-011",
    name: "Giấy in ảnh Lucky mặt mờ 0.508*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 16,
    width: 0.508,
    length: 30.0,
    kgPerUnit: 4.425,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_MO-0_508_40M-012",
    name: "Giấy in ảnh Lucky mặt mờ 0.508*40m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 17,
    width: 0.508,
    length: 40.0,
    kgPerUnit: 5.825,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_MO-0_914_30M-013",
    name: "Giấy in ảnh Lucky mặt mờ 0.914*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 18,
    width: 0.914,
    length: 30.0,
    kgPerUnit: 8.075,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_MO-0_914_40M-014",
    name: "Giấy in ảnh Lucky mặt mờ 0.914*40m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 19,
    width: 0.914,
    length: 40.0,
    kgPerUnit: 10.225,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-0_127_100M-015",
    name: "Giấy in ảnh Lucky mặt bóng 0.127*100m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 20,
    width: 0.127,
    length: 100.0,
    kgPerUnit: 3.5,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-0_51_40M-016",
    name: "Giấy in ảnh Lucky mặt bóng 0.51*40m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 21,
    width: 0.51,
    length: 40.0,
    kgPerUnit: 5.675,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-0_508_40M-017",
    name: "Giấy in ảnh Lucky mặt bóng 0.508*40m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 22,
    width: 0.508,
    length: 40.0,
    kgPerUnit: 5.75,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-0_61_40M-018",
    name: "Giấy in ảnh Lucky mặt bóng 0.61*40m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 23,
    width: 0.61,
    length: 40.0,
    kgPerUnit: 6.875,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-0_762_30M-019",
    name: "Giấy in ảnh Lucky mặt bóng 0.762*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 24,
    width: 0.762,
    length: 30.0,
    kgPerUnit: 6.9,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-0_914_30M-020",
    name: "Giấy in ảnh Lucky mặt bóng 0.914*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 25,
    width: 0.914,
    length: 30.0,
    kgPerUnit: 8.3,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-0_914_40M-021",
    name: "Giấy in ảnh Lucky mặt bóng 0.914*40m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 26,
    width: 0.914,
    length: 40.0,
    kgPerUnit: 10.275,
  },
  {
    code: "GIAY_ANH_CUON-GIAY_IN_ANH_LUCKY_MAT_BONG-1_22_30M-022",
    name: "Giấy in ảnh Lucky mặt bóng 1.22*30m",
    categoryCode: "GIAY_ANH_CUON",
    baseUnit: "cuon",
    basePrice: null,
    sheetRow: 27,
    width: 1.22,
    length: 30.0,
    kgPerUnit: 11.15,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G-A4-001",
    name: "Giấy in ảnh Kodak mặt bóng 260g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 5,
    width: 0.06237,
    length: 20.0,
    kgPerUnit: 0.316,
    sheetsPerPack: 20.0,
    packsPerBox: 50.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G-A3-002",
    name: "Giấy in ảnh Kodak mặt bóng 260g A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 6,
    width: 0.12474,
    length: 20.0,
    kgPerUnit: 0.6366666667,
    sheetsPerPack: 20.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G-A3-003",
    name: "Giấy in ảnh Kodak mặt bóng 260g A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 7,
    width: 0.12474,
    length: 20.0,
    kgPerUnit: 0.6766666667,
    sheetsPerPack: 20.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G-A3-004",
    name: "Giấy in ảnh Kodak mặt bóng 260g A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 8,
    width: 0.12474,
    length: 20.0,
    kgPerUnit: 0.6766666667,
    sheetsPerPack: 20.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_240G-A6-005",
    name: "Giấy in ảnh Kodak mặt bóng 240g A6",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 9,
    width: 0.015504,
    length: 100.0,
    kgPerUnit: 0.395,
    sheetsPerPack: 100.0,
    packsPerBox: 40.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_240G-A4-006",
    name: "Giấy in ảnh Kodak mặt bóng 240g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 10,
    width: 0.06237,
    length: 20.0,
    kgPerUnit: 0.322,
    sheetsPerPack: 20.0,
    packsPerBox: 50.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_240G-A3-007",
    name: "Giấy in ảnh Kodak mặt bóng 240g A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 11,
    width: 0.12474,
    length: 20.0,
    kgPerUnit: 0.54,
    sheetsPerPack: 20.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_240G-13_18_5R-008",
    name: "Giấy in ảnh Kodak mặt bóng 240g 13*18 - 5R",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 12,
    width: 0.022606,
    length: 100.0,
    kgPerUnit: 0.5733333333,
    sheetsPerPack: 100.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G_NEW-4R-009",
    name: "Giấy in ảnh Kodak mặt bóng 260g - NEW 4R",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 13,
    width: 0.015504,
    length: 100.0,
    kgPerUnit: 0.4325,
    sheetsPerPack: 100.0,
    packsPerBox: 40.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G_NEW-A4-010",
    name: "Giấy in ảnh Kodak mặt bóng 260g - NEW A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 14,
    width: 0.06237,
    length: 20.0,
    kgPerUnit: 0.354,
    sheetsPerPack: 20.0,
    packsPerBox: 50.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G_NEW-A3-011",
    name: "Giấy in ảnh Kodak mặt bóng 260g - NEW A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 15,
    width: 0.12474,
    length: 20.0,
    kgPerUnit: 0.6966666667,
    sheetsPerPack: 20.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_BONG_260G_NEW-13_18_5R-012",
    name: "Giấy in ảnh Kodak mặt bóng 260g - NEW 13*18 - 5R",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 16,
    width: 0.022606,
    length: 100.0,
    kgPerUnit: 0.6266666667,
    sheetsPerPack: 100.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_MO_260G-A6_4R-013",
    name: "Giấy in ảnh Kodak mặt mờ 260g A6 - 4R",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 17,
    width: 0.015504,
    length: 100.0,
    kgPerUnit: 0.4075,
    sheetsPerPack: 100.0,
    packsPerBox: 40.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_MO_260G-4R-014",
    name: "Giấy in ảnh Kodak mặt mờ 260g 4R",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 18,
    width: 0.016,
    length: 100.0,
    kgPerUnit: 0.4125,
    sheetsPerPack: 100.0,
    packsPerBox: 40.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_MO_260G-A4-015",
    name: "Giấy in ảnh Kodak mặt mờ 260g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 19,
    width: 0.06237,
    length: 20.0,
    kgPerUnit: 0.335,
    sheetsPerPack: 20.0,
    packsPerBox: 60.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_MO_260G-A4-016",
    name: "Giấy in ảnh Kodak mặt mờ 260g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 20,
    width: 0.06237,
    length: 20.0,
    kgPerUnit: 0.336,
    sheetsPerPack: 20.0,
    packsPerBox: 50.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_MO_260G-13_18_5R-017",
    name: "Giấy in ảnh Kodak mặt mờ 260g 13*18 - 5R",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 21,
    width: 0.022606,
    length: 100.0,
    kgPerUnit: 0.6,
    sheetsPerPack: 100.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_IN_ANH_KODAK_MAT_MO_260G-A3-018",
    name: "Giấy in ảnh Kodak mặt mờ 260g A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 22,
    width: 0.12474,
    length: 20.0,
    kgPerUnit: 0.6533333333,
    sheetsPerPack: 20.0,
    packsPerBox: 30.0,
  },
  {
    code: "GIAY_ANH_XAP-MIRA_BONG_260-A4-019",
    name: "Mira - bóng 260 A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 23,
    width: 0.06237,
    length: 20.0,
    kgPerUnit: 0.5,
    sheetsPerPack: 20.0,
    packsPerBox: 60.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_230-A4-020",
    name: "Giấy ảnh 1 mặt bóng - CT 230 A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 24,
    width: 0.06237,
    length: 50.0,
    kgPerUnit: 0.7285714286,
    sheetsPerPack: 50.0,
    packsPerBox: 28.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_230-21_60-021",
    name: "Giấy ảnh 1 mặt bóng - CT 230 21*60",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 25,
    width: 0.126,
    length: 50.0,
    kgPerUnit: 1.478571429,
    sheetsPerPack: 50.0,
    packsPerBox: 14.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_230-A3-022",
    name: "Giấy ảnh 1 mặt bóng - CT 230 A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 26,
    width: 0.12474,
    length: 50.0,
    kgPerUnit: 1.471428571,
    sheetsPerPack: 50.0,
    packsPerBox: 14.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_115G-A4-023",
    name: "Giấy ảnh 1 mặt bóng - CT 115g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 27,
    width: 0.06237,
    length: 50.0,
    kgPerUnit: 0.355,
    sheetsPerPack: 50.0,
    packsPerBox: 40.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_115G-A3-024",
    name: "Giấy ảnh 1 mặt bóng - CT 115g A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 28,
    width: 0.12474,
    length: 50.0,
    kgPerUnit: 0.505,
    sheetsPerPack: 50.0,
    packsPerBox: 20.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_135G-A4-025",
    name: "Giấy ảnh 1 mặt bóng - CT 135g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 29,
    width: 0.06237,
    length: 50.0,
    kgPerUnit: 0.4025,
    sheetsPerPack: 50.0,
    packsPerBox: 40.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_160G-A4-026",
    name: "Giấy ảnh 1 mặt bóng - CT 160g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 30,
    width: 0.06237,
    length: 50.0,
    kgPerUnit: 0.4875,
    sheetsPerPack: 50.0,
    packsPerBox: 40.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_180G-A4-027",
    name: "Giấy ảnh 1 mặt bóng - CT 180g A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 31,
    width: 0.06237,
    length: 100.0,
    kgPerUnit: 0.6333333333,
    sheetsPerPack: 100.0,
    packsPerBox: 20.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_1_MAT_BONG_CT_180G-A3-028",
    name: "Giấy ảnh 1 mặt bóng - CT 180g A3",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 32,
    width: 0.12474,
    length: 100.0,
    kgPerUnit: 1.255555556,
    sheetsPerPack: 100.0,
    packsPerBox: 10.0,
  },
  {
    code: "GIAY_ANH_XAP-MANG_PLASTIC-8C-029",
    name: "Màng Plastic 8C",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 33,
    width: 0.06776,
    length: 100.0,
    kgPerUnit: 1.8,
    sheetsPerPack: 100.0,
    packsPerBox: 22.0,
  },
  {
    code: "GIAY_ANH_XAP-GIAY_ANH_2_MAT_BONG_CT_300-A4-030",
    name: "Giấy ảnh 2 mặt bóng - CT 300 A4",
    categoryCode: "GIAY_ANH_XAP",
    baseUnit: "xap",
    basePrice: null,
    sheetRow: 34,
    width: 0.06237,
    length: 50.0,
    kgPerUnit: 0.99,
    sheetsPerPack: 50.0,
    packsPerBox: 20.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-21X21-001",
    name: "PVC 0.5 21x21",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 5,
    width: 0.0441,
    length: 800.0,
    kgPerUnit: 23.0,
    sheetsPerBox: 800.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-21X31-002",
    name: "PVC 0.5 21x31",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 6,
    width: 0.0651,
    length: 800.0,
    kgPerUnit: 34.4,
    sheetsPerBox: 800.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-26X26-003",
    name: "PVC 0.5 26x26",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 7,
    width: 0.0676,
    length: 800.0,
    kgPerUnit: 36.1,
    sheetsPerBox: 800.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-26X36-004",
    name: "PVC 0.5 26x36",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 8,
    width: 0.0936,
    length: 400.0,
    kgPerUnit: 25.1,
    sheetsPerBox: 400.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-26X36-005",
    name: "PVC 0.5 26x36",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 9,
    width: 0.0936,
    length: 500.0,
    kgPerUnit: 33.3,
    sheetsPerBox: 500.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-31X31-006",
    name: "PVC 0.5 31x31",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 10,
    width: 0.0961,
    length: 400.0,
    kgPerUnit: 25.1,
    sheetsPerBox: 400.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-31X31-007",
    name: "PVC 0.5 31x31",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 11,
    width: 0.0961,
    length: 500.0,
    kgPerUnit: 33.9,
    sheetsPerBox: 500.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-31X41-008",
    name: "PVC 0.5 31x41",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 12,
    width: 0.1271,
    length: 400.0,
    kgPerUnit: 33.4,
    sheetsPerBox: 400.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-63X93-009",
    name: "PVC 0.5 63x93",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 13,
    width: 0.5859,
    length: 100.0,
    kgPerUnit: 41.4,
    sheetsPerBox: 100.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_5-63X93-010",
    name: "PVC 0.5 63x93",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 14,
    width: 0.5859,
    length: 100.0,
    kgPerUnit: 41.9,
    sheetsPerBox: 100.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_HANG_AT-63X93-011",
    name: "PVC hàng đặt 63x93",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 15,
    width: 0.5859,
    length: 100.0,
    kgPerUnit: 25.1,
    sheetsPerBox: 100.0,
  },
  {
    code: "RUOT_PVC_VIEN-SOI_PVC_U9-VANG-012",
    name: "Sợi PVC - U9 VÀNG",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "m",
    basePrice: null,
    sheetRow: 16,
    width: 1.0,
    length: 600.0,
    kgPerUnit: 22.3,
    sheetsPerBox: 600.0,
  },
  {
    code: "RUOT_PVC_VIEN-SOI_PVC_U9-BAC-013",
    name: "Sợi PVC - U9 BẠC",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "m",
    basePrice: null,
    sheetRow: 17,
    width: 1.0,
    length: 600.0,
    kgPerUnit: 21.9,
    sheetsPerBox: 600.0,
  },
  {
    code: "RUOT_PVC_VIEN-SOI_PVC_U13-VANG-014",
    name: "Sợi PVC - U13 VÀNG",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "m",
    basePrice: null,
    sheetRow: 18,
    width: 1.0,
    length: 500.0,
    kgPerUnit: 22.8,
    sheetsPerBox: 500.0,
  },
  {
    code: "RUOT_PVC_VIEN-SOI_PVC_U13-BAC-015",
    name: "Sợi PVC - U13 BẠC",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "m",
    basePrice: null,
    sheetRow: 19,
    width: 1.0,
    length: 500.0,
    kgPerUnit: 22.9,
    sheetsPerBox: 500.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_3-26X36-016",
    name: "PVC 0.3 26x36",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 20,
    width: 0.0936,
    length: 600.0,
    kgPerUnit: 34.7,
    sheetsPerBox: 600.0,
  },
  {
    code: "RUOT_PVC_VIEN-PVC_0_3-63X93-017",
    name: "PVC 0.3 63x93",
    categoryCode: "RUOT_PVC_VIEN",
    baseUnit: "to",
    basePrice: null,
    sheetRow: 21,
    width: 0.5859,
    length: 100.0,
    kgPerUnit: 36.3,
    sheetsPerBox: 100.0,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-001",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 5,
    width: 2.2,
    length: 80.0,
    kgPerUnit: 41.5,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-002",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 6,
    width: 2.6,
    length: 72.0,
    kgPerUnit: 45.1,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-003",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 7,
    width: 2.6,
    length: 80.0,
    kgPerUnit: 49.1,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-004",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 8,
    width: 2.8,
    length: 70.0,
    kgPerUnit: 50.4,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-005",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 9,
    width: 2.8,
    length: 80.0,
    kgPerUnit: 54.6,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-006",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 10,
    width: 3.1,
    length: 80.0,
    kgPerUnit: 58.8,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-007",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 11,
    width: 3.1,
    length: 62.0,
    kgPerUnit: 45.7,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-008",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 12,
    width: 3.2,
    length: 80.0,
    kgPerUnit: 60.2,
  },
  {
    code: "HIFLEX-BAT_0_30MM_E_240G-009",
    name: "Bạt 0.30mm E (240G)",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 13,
    width: 3.2,
    length: 70.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-0_28MM_2_1X80_0M-010",
    name: "Bạt 0.32mm (280g) -C 0.28mm-2.1x80.0m",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 14,
    width: 2.1,
    length: 80.0,
    thicknessMm: 0.28,
    kgPerUnit: 52.5,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-011",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 15,
    width: 2.1,
    length: 63.0,
    kgPerUnit: 41.5,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-012",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 16,
    width: 2.1,
    length: 70.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-013",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 17,
    width: 2.2,
    length: 80.0,
    kgPerUnit: 54.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-014",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 18,
    width: 2.2,
    length: 69.0,
    kgPerUnit: 47.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-015",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 19,
    width: 2.6,
    length: 80.0,
    kgPerUnit: 63.1,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-016",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 20,
    width: 2.6,
    length: 65.0,
    kgPerUnit: 53.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-017",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 21,
    width: 2.8,
    length: 80.0,
    kgPerUnit: 68.9,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-018",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 22,
    width: 2.8,
    length: 74.0,
    kgPerUnit: 60.9,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-019",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 23,
    width: 3.0,
    length: 80.0,
    kgPerUnit: 72.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-020",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 24,
    width: 3.1,
    length: 65.0,
    kgPerUnit: 59.2,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-021",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 25,
    width: 3.1,
    length: 80.0,
    kgPerUnit: 75.3,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-022",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 26,
    width: 3.2,
    length: 80.0,
    kgPerUnit: 78.1,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-023",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 27,
    width: 3.2,
    length: 70.0,
    kgPerUnit: 66.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-024",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 28,
    width: 3.2,
    length: 75.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_280G_C-025",
    name: "Bạt 0.32mm (280g) -C",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 29,
    width: 3.2,
    length: 68.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-0_3MM_1_0X80_0M-026",
    name: "Bạt 0.32mm (300g) -D 0.3mm-1.0x80.0m",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 30,
    width: 1.0,
    length: 80.0,
    thicknessMm: 0.3,
    kgPerUnit: 27.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-027",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 31,
    width: 0.9,
    length: 80.0,
    kgPerUnit: 24.6,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-028",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 32,
    width: 0.9,
    length: 79.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-029",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 33,
    width: 0.9,
    length: 76.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-030",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 34,
    width: 1.3,
    length: 80.0,
    kgPerUnit: 33.2,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-031",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 35,
    width: 1.3,
    length: 70.0,
    kgPerUnit: 29.5,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-032",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 36,
    width: 1.4,
    length: 80.0,
    kgPerUnit: 35.9,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-033",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 37,
    width: 1.4,
    length: 65.0,
    kgPerUnit: 29.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-034",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 38,
    width: 1.5,
    length: 80.0,
    kgPerUnit: 38.2,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-035",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 39,
    width: 1.5,
    length: 73.0,
    kgPerUnit: 35.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-036",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 40,
    width: 1.5,
    length: 75.0,
    kgPerUnit: 36.3,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-037",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 41,
    width: 1.6,
    length: 80.0,
    kgPerUnit: 41.4,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-038",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 42,
    width: 1.6,
    length: 65.0,
    kgPerUnit: 33.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-039",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 43,
    width: 1.7,
    length: 80.0,
    kgPerUnit: 43.6,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-040",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 44,
    width: 1.7,
    length: 70.0,
    kgPerUnit: 38.6,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-041",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 45,
    width: 1.8,
    length: 80.0,
    kgPerUnit: 46.1,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-042",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 46,
    width: 1.8,
    length: 70.0,
    kgPerUnit: 42.5,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-043",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 47,
    width: 1.8,
    length: 74.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-044",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 48,
    width: 1.8,
    length: 63.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-045",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 49,
    width: 1.9,
    length: 80.0,
    kgPerUnit: 48.9,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-046",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 50,
    width: 2.0,
    length: 80.0,
    kgPerUnit: 51.9,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-047",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 51,
    width: 2.0,
    length: 72.0,
    kgPerUnit: 46.6,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-048",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 52,
    width: 2.1,
    length: 80.0,
    kgPerUnit: 53.4,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-049",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 53,
    width: 2.1,
    length: 75.0,
    kgPerUnit: 50.9,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-050",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 54,
    width: 2.1,
    length: 50.0,
    kgPerUnit: 34.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-051",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 55,
    width: 2.2,
    length: 80.0,
    kgPerUnit: 57.4,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-052",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 56,
    width: 2.2,
    length: 61.0,
    kgPerUnit: 44.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-053",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 57,
    width: 2.2,
    length: 70.0,
    kgPerUnit: 50.3,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-054",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 58,
    width: 2.3,
    length: 80.0,
    kgPerUnit: 59.1,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-055",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 59,
    width: 2.3,
    length: 70.0,
    kgPerUnit: 53.2,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-056",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 60,
    width: 2.3,
    length: 77.0,
    kgPerUnit: 57.2,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-057",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 61,
    width: 2.3,
    length: 68.0,
    kgPerUnit: 50.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-058",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 62,
    width: 2.3,
    length: 64.0,
    kgPerUnit: 48.5,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-059",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 63,
    width: 2.4,
    length: 80.0,
    kgPerUnit: 63.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-060",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 64,
    width: 2.4,
    length: 67.0,
    kgPerUnit: 52.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-061",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 65,
    width: 2.5,
    length: 80.0,
    kgPerUnit: 62.3,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-062",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 66,
    width: 2.5,
    length: 79.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-063",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 67,
    width: 2.6,
    length: 80.0,
    kgPerUnit: 66.5,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-064",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 68,
    width: 2.6,
    length: 75.0,
    kgPerUnit: 63.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-065",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 69,
    width: 2.6,
    length: 65.0,
    kgPerUnit: 54.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-066",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 70,
    width: 2.6,
    length: 66.0,
    kgPerUnit: 57.4,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-067",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 71,
    width: 2.6,
    length: 70.0,
    kgPerUnit: 58.8,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-068",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 72,
    width: 2.6,
    length: 78.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-069",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 73,
    width: 2.7,
    length: 80.0,
    kgPerUnit: 68.4,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-070",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 74,
    width: 2.7,
    length: 73.0,
    kgPerUnit: 62.6,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-071",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 75,
    width: 2.7,
    length: 60.0,
    kgPerUnit: 52.3,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-072",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 76,
    width: 2.8,
    length: 80.0,
    kgPerUnit: 72.1,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-073",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 77,
    width: 2.8,
    length: 70.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-074",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 78,
    width: 2.9,
    length: 80.0,
    kgPerUnit: 73.4,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-075",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 79,
    width: 3.0,
    length: 80.0,
    kgPerUnit: 75.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-076",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 80,
    width: 3.0,
    length: 75.0,
    kgPerUnit: 71.8,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-077",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 81,
    width: 3.0,
    length: 65.0,
    kgPerUnit: 71.8,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-078",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 82,
    width: 3.1,
    length: 80.0,
    kgPerUnit: 80.2,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-079",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 83,
    width: 3.1,
    length: 74.0,
    kgPerUnit: 74.6,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-080",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 84,
    width: 3.2,
    length: 80.0,
    kgPerUnit: 82.5,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-081",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 85,
    width: 3.2,
    length: 73.0,
    kgPerUnit: 75.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-082",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 86,
    width: 3.2,
    length: 60.0,
    kgPerUnit: 63.7,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-083",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 87,
    width: 3.2,
    length: 65.0,
    kgPerUnit: 67.4,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-084",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 88,
    width: 3.2,
    length: 75.0,
    kgPerUnit: 78.8,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-085",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 89,
    width: 3.2,
    length: 63.0,
  },
  {
    code: "HIFLEX-BAT_0_32MM_300G_D-086",
    name: "Bạt 0.32mm (300g) -D",
    categoryCode: "HIFLEX",
    baseUnit: "cai",
    basePrice: null,
    sheetRow: 90,
    width: 3.2,
    length: 60.0,
  },
];
